# Generated by Django 4.2.6 on 2023-10-21 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('razon_social', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=255)),
                ('RFC', models.CharField(max_length=13)),
                ('descripcion', models.TextField()),
                ('banco', models.CharField(max_length=255)),
                ('cuenta_banco', models.CharField(max_length=20)),
                ('clave_banco', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proovedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactos.proveedor')),
            ],
        ),
    ]
