# Generated by Django 4.2.6 on 2023-10-24 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='clave_banco',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='cuenta_banco',
        ),
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=255)),
                ('cuenta_banco', models.CharField(max_length=20)),
                ('clave_banco', models.CharField(max_length=20)),
                ('proovedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactos.proveedor')),
            ],
        ),
    ]
