# Generated by Django 4.2.6 on 2023-10-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_remove_proveedor_banco_remove_proveedor_clave_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='unidad',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
