# Generated by Django 4.2.6 on 2024-01-06 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0004_rename_proovedor_banca_proveedor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='RFC',
            new_name='coderfc',
        ),
    ]
