# Generated by Django 4.2.6 on 2024-01-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0006_alter_proveedor_correo_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
