# Generated by Django 4.2.6 on 2023-11-08 21:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('dependencia', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('p_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_importes', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_importes_mod', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('rol', models.CharField(choices=[('Admin', 'Admin'), ('Consul', 'Consul')], default='Consul', max_length=10)),
            ],
            options={
                'permissions': [('can_view_gastos', 'Puede ver gastos'), ('can_add_edit_delete_gastos', 'Puede agregar, editar y eliminar gastos')],
            },
        ),
        migrations.CreateModel(
            name='Volumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=255)),
                ('concepto', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('Sin cambio', 'Sin cambio'), ('Deduccion', 'Deduccion'), ('Adicional', 'Adicional'), ('Extraordinario', 'Extraordinario')], default='Sin cambio', max_length=30)),
                ('volumen', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('v_mod', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('importe_mod', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Obra.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fvence', models.DateField(blank=True, null=True)),
                ('Fcreado', models.DateField(default=django.utils.timezone.now)),
                ('Fcompletado', models.DateField(blank=True, editable=False, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('no_completado', 'No Completado'), ('vencida', 'Vencida')], default='no_completado', max_length=15)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Obra.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('proveedor', models.CharField(max_length=255, null=True)),
                ('concepto', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('Administracion', 'Administración'), ('Mano de obra', 'Mano de obra'), ('Materiales', 'Materiales'), ('Viaticos', 'Viáticos'), ('Varios', 'Varios')], max_length=25)),
                ('facturado', models.CharField(choices=[('Facturado', 'Facturado'), ('No Facturado', 'No Facturado')], default='No Facturado', max_length=50)),
                ('Tipo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=50)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Obra.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('archivo', models.ImageField(upload_to='galeria/')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Obra.obra')),
            ],
        ),
    ]
