# Generated by Django 4.2.6 on 2023-10-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('localida', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('dependencia', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('p_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
