# Generated by Django 4.2.6 on 2024-02-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='total_diferencia',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
