# Generated by Django 4.2.6 on 2023-10-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0002_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='obras',
            field=models.ManyToManyField(related_name='usuarios', to='Obra.obra'),
        ),
    ]
