# Generated by Django 4.2.6 on 2023-10-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0003_usuario_obras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='fecha',
            field=models.DateField(),
        ),
    ]
