# Generated by Django 4.2.6 on 2024-02-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0004_alter_abono_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumen',
            name='importe_mod',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='volumen',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
