# Generated by Django 4.2.6 on 2023-10-17 05:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0004_alter_obra_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fvence', models.DateField(blank=True, null=True)),
                ('Fcreado', models.DateTimeField(default=django.utils.timezone.now)),
                ('Fcompletado', models.DateField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('no_completado', 'No Completado'), ('vencida', 'Vencida')], default='no_completado', max_length=15)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Obra.obra')),
            ],
        ),
    ]
