# Generated by Django 4.2.6 on 2024-03-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0005_alter_volumen_importe_mod_alter_volumen_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='total_abonos',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
