# Generated by Django 4.2.6 on 2023-10-17 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0005_tarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='localida',
            new_name='localidad',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='Fcreado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
