# Generated by Django 4.2.6 on 2023-10-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0007_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='total_importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
