# Generated by Django 4.2.6 on 2023-10-18 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0008_gasto_total_importe'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Obra.obra'),
        ),
    ]
