# Generated by Django 4.2.6 on 2023-10-18 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0009_gasto_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='obra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Obra.obra'),
            preserve_default=False,
        ),
    ]
