# Generated by Django 4.2.6 on 2023-10-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0011_alter_gasto_total_importe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='total_importe',
        ),
        migrations.AddField(
            model_name='gasto',
            name='total_gastos',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
