# Generated by Django 4.2.6 on 2023-10-19 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0012_remove_gasto_total_importe_gasto_total_gastos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('archivo', models.ImageField(upload_to='galeria/')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Obra.obra')),
            ],
        ),
    ]
