# Generated by Django 4.2.6 on 2023-10-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0013_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='facturado',
            field=models.CharField(choices=[('Facturado', 'Facturado'), ('No Facturado', 'No Facturado')], default='No Facturado', max_length=255),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='fecha',
            field=models.DateField(),
        ),
    ]
