# Generated by Django 4.2.6 on 2023-10-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0014_gasto_facturado_alter_galeria_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='total_gastos',
        ),
        migrations.AddField(
            model_name='obra',
            name='total_gastos',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='obra',
            name='p_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
