# Generated by Django 4.2.6 on 2023-10-20 21:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0015_remove_gasto_total_gastos_obra_total_gastos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Volumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('unidad', models.CharField(max_length=255)),
                ('concepto', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('volumen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('v_mod', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('importe_mod', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumenes', to='Obra.obra')),
            ],
        ),
    ]
