# Generated by Django 4.2.6 on 2023-10-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0016_alter_gasto_fecha_volumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumen',
            name='estado',
            field=models.CharField(choices=[('Extraordinario', 'Extraordinario'), ('Adicional', 'Adicional'), ('Deduccion', 'Deduccion'), ('Sin cambio', 'Sin cambio')], default='Sin cambio', max_length=30),
        ),
    ]
