# Generated by Django 4.2.6 on 2023-10-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0017_alter_volumen_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumen',
            name='estado',
            field=models.CharField(choices=[('Sin cambio', 'Sin cambio'), ('Deduccion', 'Deduccion'), ('Extraordinario', 'Extraordinario'), ('Adicional', 'Adicional')], default='Sin cambio', max_length=30),
        ),
    ]
