# Generated by Django 4.2.6 on 2023-10-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0018_alter_volumen_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='Tipo',
            field=models.CharField(choices=[('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo')], default='Efectivo', max_length=50),
        ),
        migrations.AddField(
            model_name='gasto',
            name='proveedor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='facturado',
            field=models.CharField(choices=[('Facturado', 'Facturado'), ('No Facturado', 'No Facturado')], default='No Facturado', max_length=50),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='Fcompletado',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='volumen',
            name='estado',
            field=models.CharField(choices=[('Sin cambio', 'Sin cambio'), ('Deduccion', 'Deduccion'), ('Adicional', 'Adicional'), ('Extraordinario', 'Extraordinario')], default='Sin cambio', max_length=30),
        ),
    ]
