# Generated by Django 4.2.6 on 2023-10-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0019_gasto_tipo_gasto_proveedor_alter_gasto_facturado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumen',
            name='dif_contrato',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='volumen',
            name='dif_ejecutado',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='volumen',
            name='estado',
            field=models.CharField(choices=[('Extraordinario', 'Extraordinario'), ('Adicional', 'Adicional'), ('Sin cambio', 'Sin cambio'), ('Deduccion', 'Deduccion')], default='Sin cambio', max_length=30),
        ),
    ]
