# Generated by Django 4.2.6 on 2023-10-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0020_volumen_dif_contrato_volumen_dif_ejecutado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='Tipo',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='volumen',
            name='estado',
            field=models.CharField(choices=[('Deduccion', 'Deduccion'), ('Sin cambio', 'Sin cambio'), ('Extraordinario', 'Extraordinario'), ('Adicional', 'Adicional')], default='Sin cambio', max_length=30),
        ),
    ]
