# Generated by Django 4.2.6 on 2023-10-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0021_alter_gasto_tipo_alter_volumen_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volumen',
            old_name='dif_contrato',
            new_name='diferencia',
        ),
        migrations.RenameField(
            model_name='volumen',
            old_name='dif_ejecutado',
            new_name='total_contrato',
        ),
        migrations.AddField(
            model_name='volumen',
            name='total_ejecutado',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='Tipo',
            field=models.CharField(choices=[('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo')], default='Efectivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='volumen',
            name='estado',
            field=models.CharField(choices=[('Adicional', 'Adicional'), ('Extraordinario', 'Extraordinario'), ('Sin cambio', 'Sin cambio'), ('Deduccion', 'Deduccion')], default='Sin cambio', max_length=30),
        ),
    ]
