# Generated by Django 4.2.6 on 2023-10-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0022_rename_dif_contrato_volumen_diferencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumen',
            name='estado',
            field=models.CharField(choices=[('Sin cambio', 'Sin cambio'), ('Extraordinario', 'Extraordinario'), ('Adicional', 'Adicional'), ('Deduccion', 'Deduccion')], default='Sin cambio', max_length=30),
        ),
    ]
