# Generated by Django 4.2.6 on 2023-10-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0026_remove_volumen_diferencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='Tipo',
            field=models.CharField(choices=[('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo')], default='Efectivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='volumen',
            name='estado',
            field=models.CharField(choices=[('Sin cambio', 'Sin cambio'), ('Adicional', 'Adicional'), ('Extraordinario', 'Extraordinario'), ('Deduccion', 'Deduccion')], default='Sin cambio', max_length=30),
        ),
    ]
