# Generated by Django 4.2.6 on 2023-10-23 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0028_alter_gasto_tipo_alter_volumen_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumen',
            name='estado',
            field=models.CharField(choices=[('Deduccion', 'Deduccion'), ('Sin cambio', 'Sin cambio'), ('Adicional', 'Adicional'), ('Extraordinario', 'Extraordinario')], default='Sin cambio', max_length=30),
        ),
        migrations.AlterField(
            model_name='volumen',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Obra.obra'),
        ),
    ]
