# Generated by Django 4.2.6 on 2023-10-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0029_alter_volumen_estado_alter_volumen_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumen',
            name='estado',
            field=models.CharField(choices=[('Sin cambio', 'Sin cambio'), ('Extraordinario', 'Extraordinario'), ('Deduccion', 'Deduccion'), ('Adicional', 'Adicional')], default='Sin cambio', max_length=30),
        ),
    ]
