# Generated by Django 4.2.6 on 2023-10-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0031_remove_obra_diferencia_remove_obra_total_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='Tipo',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=50),
        ),
        migrations.AlterField(
            model_name='volumen',
            name='estado',
            field=models.CharField(choices=[('Sin cambio', 'Sin cambio'), ('Deduccion', 'Deduccion'), ('Adicional', 'Adicional'), ('Extraordinario', 'Extraordinario')], default='Sin cambio', max_length=30),
        ),
    ]
