# Generated by Django 4.2.6 on 2023-10-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0032_alter_gasto_tipo_alter_volumen_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumen',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
