# Generated by Django 4.2.6 on 2023-10-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0033_volumen_diferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='total_importes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='obra',
            name='total_importes_mod',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
