# Generated by Django 4.2.6 on 2023-10-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0034_obra_total_importes_obra_total_importes_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='total_importes',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='obra',
            name='total_importes_mod',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
