# Generated by Django 4.2.6 on 2023-10-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0035_alter_obra_total_importes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumen',
            name='volumen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
