# Generated by Django 4.2.6 on 2023-10-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0039_remove_usuario_groups_remove_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='confirm_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
