# Generated by Django 4.2.6 on 2023-11-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obra', '0041_remove_usuario_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='Usuario01', max_length=150, unique=True),
        ),
    ]
